DROP TABLE IF EXISTS angebot CASCADE;
CREATE TABLE IF NOT EXISTS angebot
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    behart varchar(50) DEFAULT NULL,
    betrag float       DEFAULT NULL
);

TRUNCATE TABLE angebot;
INSERT INTO angebot (behart, betrag)
VALUES ('behKurz', 50),
       ('behMittel', 85),
       ('behLang', 90);